// <auto-generated />
using System;
using MagazineAPInfrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagazineAPInfrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916193358_AddStockDocumentConstraints")]
    partial class AddStockDocumentConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagazineAPIDomain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Contractor", b =>
                {
                    b.Property<Guid>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ContractorID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ContractorId");

                    b.ToTable("Contractors", (string)null);
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InventoryID");

                    b.Property<decimal>("AvailableQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasComputedColumnSql("[Quantity] - [ReservedQuantity]", true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationID");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductID");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("InventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId", "LocationId")
                        .IsUnique();

                    b.ToTable("Inventory", null, t =>
                        {
                            t.HasCheckConstraint("CK_Inventory_QuantityValues", "[Quantity] >= 0 AND [ReservedQuantity] >= 0 AND [ReservedQuantity] <= [Quantity]");
                        });
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WarehouseID");

                    b.HasKey("LocationId");

                    b.HasIndex("WarehouseId", "LocationCode")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "products.read",
                            Description = "Wyświetlanie katalogu i szczegółów produktów.",
                            Name = "Podgląd produktów"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "products.manage",
                            Description = "Dodawanie, edycja i wycofywanie produktów.",
                            Name = "Zarządzanie produktami"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "inventory.read",
                            Description = "Wyświetlanie stanów i rezerwacji magazynowych.",
                            Name = "Podgląd stanów"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "inventory.manage",
                            Description = "Przyjęcia, wydania, przesunięcia i korekty stanów.",
                            Name = "Zarządzanie stanami"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "warehouses.read",
                            Description = "Wyświetlanie magazynów oraz lokalizacji.",
                            Name = "Podgląd magazynów"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Code = "warehouses.manage",
                            Description = "Dodawanie i edycja magazynów oraz lokalizacji.",
                            Name = "Zarządzanie magazynami"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Code = "contractors.read",
                            Description = "Wyświetlanie dostawców i odbiorców.",
                            Name = "Podgląd kontrahentów"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Code = "contractors.manage",
                            Description = "Dodawanie i edycja kontrahentów.",
                            Name = "Zarządzanie kontrahentami"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Code = "users.read",
                            Description = "Wyświetlanie kont użytkowników.",
                            Name = "Podgląd użytkowników"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Code = "users.manage",
                            Description = "Edycja i usuwanie kont innych niż administratorzy.",
                            Name = "Zarządzanie użytkownikami"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Code = "dictionaries.manage",
                            Description = "Edycja kategorii i jednostek miary.",
                            Name = "Zarządzanie słownikami"
                        });
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductID");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SKU");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UnitOfMeasureID");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_Prices", "[PurchasePrice] >= 0 AND [SalePrice] >= 0");
                        });
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Kierownik"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Pracownik"
                        });
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.StockDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockDocuments", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockDocuments_Status", "[Status] IN (1, 2)");

                            t.HasCheckConstraint("CK_StockDocuments_Type", "[Type] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.StockDocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("StockDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockDocumentId", "ProductId", "LocationId")
                        .IsUnique();

                    b.ToTable("StockDocumentItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockDocumentItems_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("UnitOfMeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UnitOfMeasureID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UnitOfMeasureId");

                    b.ToTable("UnitsOfMeasure", (string)null);
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleID");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WarehouseID");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_WarehouseAssignment", "[RoleID] = '10000000-0000-0000-0000-000000000001' OR [WarehouseID] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WarehouseID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Inventory", b =>
                {
                    b.HasOne("MagazineAPIDomain.Entities.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazineAPIDomain.Entities.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Location", b =>
                {
                    b.HasOne("MagazineAPIDomain.Entities.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Product", b =>
                {
                    b.HasOne("MagazineAPIDomain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazineAPIDomain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.RolePermission", b =>
                {
                    b.HasOne("MagazineAPIDomain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazineAPIDomain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.StockDocument", b =>
                {
                    b.HasOne("MagazineAPIDomain.Entities.Contractor", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazineAPIDomain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazineAPIDomain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.StockDocumentItem", b =>
                {
                    b.HasOne("MagazineAPIDomain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazineAPIDomain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazineAPIDomain.Entities.StockDocument", "StockDocument")
                        .WithMany("Items")
                        .HasForeignKey("StockDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("StockDocument");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.User", b =>
                {
                    b.HasOne("MagazineAPIDomain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazineAPIDomain.Entities.Warehouse", "Warehouse")
                        .WithMany("Users")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Location", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.StockDocument", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MagazineAPIDomain.Entities.Warehouse", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
